# Generated by Django 5.2.15 on 2026-06-08 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpersonationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('start', 'Start'), ('stop', 'Stop')], max_length=10)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('impersonated', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonation_events', to=settings.AUTH_USER_MODEL)),
                ('impersonator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impersonations_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
