# Generated by Django 5.2.15 on 2026-06-09 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0003_serviceaccount_created_by_serviceaccount_keycloak_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('url_analyze', 'URL analysis')], db_index=True, max_length=40)),
                ('version', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=200)),
                ('system_prompt', models.TextField(help_text='The editable instruction text sent to the model.')),
                ('model', models.CharField(default='sonnet-4.6', help_text='OpenRouter model alias (see recommendations.llm.LLMClient.MODELS).', max_length=60)),
                ('temperature', models.FloatField(default=0.4)),
                ('is_champion', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['task_type', '-version'],
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fetching', 'Fetching'), ('generating', 'Generating'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('model', models.CharField(blank=True, max_length=60)),
                ('fetched_title', models.CharField(blank=True, max_length=1000)),
                ('fetched_meta', models.TextField(blank=True)),
                ('page_text', models.TextField(blank=True)),
                ('page_content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_analyses', to='tenancy.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_analyses', to='tenancy.project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_analyses', to=settings.AUTH_USER_MODEL)),
                ('prompt_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='recommendations.promptversion')),
            ],
            options={
                'verbose_name_plural': 'analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('new_content', 'New content'), ('existing_content', 'Existing content'), ('metadata', 'Metadata'), ('technical', 'Technical'), ('schema', 'Schema'), ('aeo_readiness', 'AEO readiness'), ('authority', 'Authority'), ('accessibility', 'Accessibility')], max_length=20)),
                ('action_type', models.CharField(choices=[('generate_content', 'Generate content'), ('expand_content', 'Expand content'), ('refresh_content', 'Refresh content'), ('generate_metadata', 'Generate metadata'), ('generate_schema', 'Generate schema'), ('generate_faq', 'Generate FAQ'), ('improve_readability', 'Improve readability'), ('fix_technical', 'Fix technical issue'), ('fix_accessibility', 'Fix accessibility'), ('fix_internal_links', 'Fix internal links'), ('optimize_aeo', 'Optimize for answer engines'), ('target_snippet', 'Target featured snippet'), ('inject_authority', 'Inject authority signals')], max_length=30)),
                ('title', models.CharField(max_length=500)),
                ('why', models.TextField(blank=True, help_text='Data-backed reasoning for the recommendation.')),
                ('description', models.TextField(blank=True, help_text='What to do.')),
                ('effort', models.CharField(choices=[('one_click', 'One click'), ('review', 'Review'), ('dev_required', 'Dev required'), ('external', 'External')], default='review', max_length=20)),
                ('priority_score', models.FloatField(db_index=True, default=0)),
                ('impact_label', models.CharField(blank=True, max_length=100)),
                ('effort_label', models.CharField(blank=True, max_length=100)),
                ('action_payload', models.JSONField(blank=True, default=dict)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommendations.analysis')),
            ],
            options={
                'ordering': ['analysis', 'position'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('viewed', 'Viewed'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed'), ('applied', 'Applied')], max_length=20)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_interactions', to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='recommendations.recommendation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='promptversion',
            constraint=models.UniqueConstraint(fields=('task_type', 'version'), name='unique_prompt_version_per_task'),
        ),
        migrations.AddConstraint(
            model_name='promptversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_champion', True)), fields=('task_type',), name='one_champion_per_task'),
        ),
    ]
