# Generated by Django 5.2.15 on 2026-06-09 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_seed_url_analyze_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('title', models.CharField(blank=True, max_length=1000)),
                ('meta', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('content_hash', models.CharField(max_length=64, unique=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.AddField(
            model_name='analysis',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='recommendations.pagesnapshot'),
        ),
    ]
