# Generated by Django 5.2.15 on 2026-06-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_backfill_page_snapshots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='fetched_meta',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='fetched_title',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='page_content_hash',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='page_text',
        ),
    ]
