# Generated by Django 5.2.15 on 2026-06-09 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_drop_analysis_page_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='created_at',
        ),
    ]
