# Generated by Django 5.2.15 on 2026-06-08 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_serviceaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaccount',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_accounts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceaccount',
            name='keycloak_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
