# Generated by Django 5.2.15 on 2026-06-09 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_serviceaccount_created_by_serviceaccount_keycloak_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
    ]
