# Generated by Django 6.0.6 on 2026-06-18 02:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_key', models.CharField(max_length=512)),
                ('poster_key', models.CharField(blank=True, max_length=512)),
                ('mime', models.CharField(blank=True, max_length=128)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('ocr_text', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='clips_asset_owner_i_1a79f1_idx')],
            },
        ),
    ]
