# Generated by Django 6.0.6 on 2026-06-18 12:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0002_asset_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image_key', models.CharField(max_length=512)),
                ('mime', models.CharField(blank=True, max_length=128)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(default='imgflip', max_length=32)),
                ('source_id', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_id'), name='uniq_template_source')],
            },
        ),
    ]
