# Generated by Django 6.0.6 on 2026-06-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0003_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
