# Generated by Django 6.0.6 on 2026-06-18 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0004_asset_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='has_audio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=8),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('transcoding', 'Transcoding'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.CreateModel(
            name='Rendition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('av1', 'AV1'), ('vp9', 'VP9'), ('h264', 'H.264'), ('poster', 'Poster'), ('sprite', 'Scrub sprite')], max_length=8)),
                ('r2_key', models.CharField(max_length=512)),
                ('mime', models.CharField(blank=True, max_length=128)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='clips.asset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('asset', 'kind'), name='uniq_asset_rendition_kind')],
            },
        ),
    ]
