# Generated by Django 6.0.6 on 2026-06-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0005_asset_duration_asset_has_audio_asset_media_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='caption_layers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='asset',
            name='text_layer_key',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
