# Generated by Django 6.0.6 on 2026-06-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0007_alter_rendition_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendition',
            name='kind',
            field=models.CharField(choices=[('av1', 'AV1'), ('vp9', 'VP9'), ('h264', 'H.264'), ('gif', 'GIF (chat autoplay)'), ('captioned', 'Captioned (caption burned in)'), ('poster', 'Poster'), ('sprite', 'Scrub sprite')], max_length=12),
        ),
    ]
