# Generated by Django 6.0.6 on 2026-06-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0008_alter_rendition_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='crop',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
