# Generated by Django 6.0.6 on 2026-06-19 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0009_asset_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='caption_burning',
            field=models.BooleanField(default=False),
        ),
    ]
