# Generated by Django 6.0.6 on 2026-06-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0010_asset_caption_burning'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='trim_end',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='trim_start',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
