# Generated by Django 6.0.6 on 2026-06-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0011_asset_trim_end_asset_trim_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='transcode_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
