# Generated by Django 6.0.6 on 2026-06-20 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0012_asset_transcode_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='from_recorder',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='remixed_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remixes', to='clips.asset'),
        ),
    ]
